# on-board system oscillator
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {clk}]

# control 
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33}  [get_ports {rst}]

##input
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {we}]
## [15:0]  SeqData
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[0]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[1]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[2]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[3]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[4]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[5]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[6]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[7]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[8]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[9]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[10]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[11]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[12]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[13]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[14]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {SeqData[15]}]

##Output
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {valid}]
## [75:0] AllanVariance
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[0]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[1]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[2]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[3]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[4]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[5]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[6]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[7]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[8]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[9]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[10]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[11]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[12]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[13]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[14]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[15]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[16]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[17]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[18]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[19]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[20]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[21]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[22]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[23]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[24]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[25]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[26]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[27]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[28]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[29]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[30]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[31]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[32]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[33]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[34]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[35]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[36]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[37]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[38]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[39]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[40]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[41]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[42]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[43]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[44]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[45]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[46]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[47]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[48]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[49]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[50]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[51]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[52]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[53]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[54]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[55]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[56]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[57]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[58]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[59]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[60]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[61]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[62]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[63]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[64]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[65]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[66]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[67]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[68]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[69]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[70]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[71]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[72]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[73]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[74]}]
#set_property -dict {PACKAGE_PIN  IOSTANDARD LVCMOS33}  [get_ports {AllanVariance[75]}]